services:
  - type: web
    name: hostyria
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOSTYRIA_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: NPM_CONFIG_PRODUCTION
        value: false
